### ISSUE TITLE
Textbox does not appear after preanim

### ISSUE THREAD

**Issue by MochiB01** [AttorneyOnline/webAO#139] opened 2022-04-02 21:39 UTC
I have found that when A pre animation is enabled and done. After the pre animation is done, the text box is not visible.

**Comment by PotatoDC** [comment] 2022-04-02 22:24
I did a preanim and it showed the preanim, but it never displayed the text I posted which was my iconic 
![Screenshot_2022-04-03-01-17-47-438](https://user-images.githubusercontent.com/102555677/161403262-55c4111c-6a62-4b6f-8013-0e78f0815eab.jpeg)
"Wh" or even the textbox

**Comment by stonedDiscord** [comment] 2022-04-03 00:30
this issue appeared after we merged the noninterrupting preanims
i am aware of it and still trying to figure out the cause

i have a suspicion and i'm working on it

**Closed** 2022-05-10 12:07 UTC
